swagger: '2.0'
basePath: '/'
info:
  title: Data Object Service
  version: 0.1.0
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /ga4gh/dos/v1/databundles:
    post:
      summary: Create a new Data Bundle
      operationId: CreateDataBundle
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CreateDataBundleResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateDataBundleRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  /ga4gh/dos/v1/databundles/list:
    post:
      summary: List the Data Bundles
      operationId: ListDataBundles
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListDataBundlesResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ListDataBundlesRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  '/ga4gh/dos/v1/databundles/{data_bundle_id}':
    get:
      summary: Retrieve a Data Bundle
      operationId: GetDataBundle
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/GetDataBundleResponse'
      parameters:
        - name: data_bundle_id
          in: path
          required: true
          type: string
        - name: version
          description: |-
            OPTIONAL
            If provided will return the requested version of the selected Data Bundle.
            Otherwise, only the latest version is returned.
          in: query
          required: false
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
    delete:
      summary: Delete a Data Bundle
      operationId: DeleteDataBundle
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/DeleteDataBundleResponse'
      parameters:
        - name: data_bundle_id
          in: path
          required: true
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
    put:
      summary: Update a Data Bundle
      operationId: UpdateDataBundle
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/UpdateDataBundleResponse'
      parameters:
        - name: data_bundle_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateDataBundleRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  '/ga4gh/dos/v1/databundles/{data_bundle_id}/versions':
    get:
      operationId: GetDataBundleVersions
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/GetDataBundleVersionsResponse'
      parameters:
        - name: data_bundle_id
          in: path
          required: true
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  /ga4gh/dos/v1/dataobjects:
    post:
      summary: Make a new Data Object
      operationId: CreateDataObject
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CreateDataObjectResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateDataObjectRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  /ga4gh/dos/v1/dataobjects/list:
    post:
      summary: List the Data Objects
      operationId: ListDataObjects
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListDataObjectsResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ListDataObjectsRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  '/ga4gh/dos/v1/dataobjects/{data_object_id}':
    get:
      summary: Retrieve a Data Object
      operationId: GetDataObject
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/GetDataObjectResponse'
      parameters:
        - name: data_object_id
          in: path
          required: true
          type: string
        - name: version
          description: |-
            OPTIONAL
            If provided will return the requested version of the selected Data Object.
          in: query
          required: false
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
    delete:
      summary: Delete a Data Object index entry
      operationId: DeleteDataObject
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/DeleteDataObjectResponse'
      parameters:
        - name: data_object_id
          in: path
          required: true
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
    put:
      summary: Update a Data Object
      operationId: UpdateDataObject
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/UpdateDataObjectResponse'
      parameters:
        - name: data_object_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateDataObjectRequest'
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
  '/ga4gh/dos/v1/dataobjects/{data_object_id}/versions':
    get:
      operationId: GetDataObjectVersions
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/GetDataObjectVersionsResponse'
      parameters:
        - name: data_object_id
          in: path
          required: true
          type: string
      tags:
        - DataObjectService
      x-swagger-router-controller: ga4gh.dos.server
definitions:
  SystemMetadata:
    description: |-
            OPTIONAL
            These values are reported by the underlying object store.
            A set of key-value pairs that represent system metadata about the object.
  UserMetadata:
    description: |-
            OPTIONAL
            A set of key-value pairs that represent metadata provided by the uploader.
  Checksum:
    type: object
    properties:
      checksum:
        type: string
        description: |-
          REQUIRED
          The hex-string encoded checksum for the Data.
      type:
        type: string
        description: |-
          OPTIONAL
          The digest method used to create the checksum. If left unspecified md5
          will be assumed.

          possible values:
          md5                # most blob stores provide a checksum using this
          multipart-md5      # multipart uploads provide a specialized tag in S3
          sha256
          sha512
  ChecksumRequest:
    type: object
    properties:
      checksum:
        type: string
        description: |-
          REQUIRED
          The hexlified checksum that one would like to match on.
      type:
        type: string
        description: |-
          OPTIONAL
          If provided will restrict responses to those that match the provided
          type.

          possible values:
          md5                # most blob stores provide a checksum using this
          multipart-md5      # multipart uploads provide a specialized tag in S3
          sha256
          sha512
  CreateDataBundleRequest:
    type: object
    properties:
      data_bundle:
        $ref: '#/definitions/DataBundle'
  CreateDataBundleResponse:
    type: object
    properties:
      data_bundle_id:
        type: string
        description: |-
          REQUIRED
          The identifier of the Data Bundle created.
  CreateDataObjectRequest:
    type: object
    properties:
      data_object:
        $ref: '#/definitions/DataObject'
        description: |-
          REQUIRED
          The data object to be created. The ID scheme is left up to the
          implementor but should be unique to the server instance.
    description: |-
      The Data Object one would like to index. One must provide any aliases
      and URLs to this file when sending the CreateDataObjectRequest. It is up
      to implementations to validate that the Data Object is available from
      the provided URLs.
  CreateDataObjectResponse:
    type: object
    properties:
      data_object_id:
        type: string
        description: The ID of the created Data Object.
  DataBundle:
    type: object
    properties:
      id:
        type: string
        title: |-
          REQUIRED
          An identifier, unique to this Data Bundle
      data_object_ids:
        type: array
        items:
          type: string
        description: |-
          REQUIRED
          The list of Data Objects that this Data Bundle contains.
      created:
        type: string
        format: date-time
        description: |-
          REQUIRED
          Timestamp of object creation in RFC3339.
      updated:
        type: string
        format: date-time
        description: |-
          REQUIRED
          Timestamp of update in RFC3339, identical to create timestamp in systems
          that do not support updates.
      version:
        type: string
        description: |-
          REQUIRED
          A string representing a version, some systems may use checksum, a RFC3339
          timestamp, or incrementing version number. For systems that do not support
          versioning please use your update timestamp as your version.
      checksums:
        type: array
        items:
          $ref: '#/definitions/Checksum'
        description: |-
          REQUIRED
          At least one checksum must be provided.
          The data bundle checksum is computed over all the checksums of the
          Data Objects that bundle contains.
      description:
        type: string
        description: |-
          OPTIONAL
          A human readable description.
      aliases:
        type: array
        items:
          type: string
        description: |-
          OPTIONAL
          A list of strings that can be used to identify this Data Bundle.
      system_metadata:
        $ref: '#/definitions/SystemMetadata'
      user_metadata:
        $ref: '#/definitions/UserMetadata'
    title: 'Data Bundle: A collection of Data Objects'
  DataObject:
    type: object
    properties:
      id:
        type: string
        description: |-
          REQUIRED
          An identifier unique to this Data Object.
      name:
        type: string
        description: |-
          OPTIONAL
          A string that can be optionally used to name a Data Object.
      size:
        type: string
        format: int64
        description: |-
          REQUIRED
          The computed size in bytes.
      created:
        type: string
        format: date-time
        description: |-
          REQUIRED
          Timestamp of object creation in RFC3339.
      updated:
        type: string
        format: date-time
        description: |-
          OPTIONAL
          Timestamp of update in RFC3339, identical to create timestamp in systems
          that do not support updates.
      version:
        type: string
        description: |-
          OPTIONAL
          A string representing a version.
      mime_type:
        type: string
        description: |-
          OPTIONAL
          A string providing the mime-type of the Data Object.
          For example, "application/json".
      checksums:
        type: array
        items:
          $ref: '#/definitions/Checksum'
        description: |-
          REQUIRED
          The checksum of the Data Object. At least one checksum must be provided.
      urls:
        type: array
        items:
          $ref: '#/definitions/URL'
        description: |-
          OPTIONAL
          The list of URLs that can be used to access the Data Object.
      description:
        type: string
        description: |-
          OPTIONAL
          A human readable description of the contents of the Data Object.
      aliases:
        type: array
        items:
          type: string
        title: |-
          OPTIONAL
          A list of strings that can be used to find this Data Object.
          These aliases can be used to represent the Data Object's location in
          a directory (e.g. "bucket/folder/file.name") to make Data Objects
          more discoverable. They might also be used to represent
    title: 'Data Object: a file, API or other resource'
  DeleteDataBundleResponse:
    type: object
    properties:
      data_bundle_id:
        type: string
  DeleteDataObjectResponse:
    type: object
    properties:
      data_object_id:
        type: string
        description: |-
          REQUIRED
          The identifier of the Data Object deleted.
  GetDataBundleResponse:
    type: object
    properties:
      data_bundle:
        $ref: '#/definitions/DataBundle'
  GetDataBundleVersionsResponse:
    type: object
    properties:
      data_bundles:
        type: array
        items:
          $ref: '#/definitions/DataBundle'
        description: |-
          REQUIRED
          All versions of the Data Bundles that match the GetDataBundleVersions
          request.
  GetDataObjectResponse:
    type: object
    properties:
      data_object:
        $ref: '#/definitions/DataObject'
        description: |-
          REQUIRED
          The Data Object that coincides with a specific GetDataObjectRequest.
  GetDataObjectVersionsResponse:
    type: object
    properties:
      data_objects:
        type: array
        items:
          $ref: '#/definitions/DataObject'
        description: |-
          REQUIRED
          All versions of the Data Objects that match the GetDataObjectVersions
          request.
  ListDataBundlesRequest:
    type: object
    properties:
      alias:
        type: string
        description: |-
          OPTIONAL
          If provided returns Data Bundles that have any alias that matches the
          request.
      checksum:
        $ref: '#/definitions/Checksum'
        description: |-
          OPTIONAL
          If provided, will only return Data Bundles which have the provided
          checksum.
      page_size:
        type: integer
        format: int32
        description: |-
          OPTIONAL
          Specifies the maximum number of results to return in a single page.
          If unspecified, a system default will be used.
      page_token:
        type: string
        description: |-
          OPTIONAL
          The continuation token, which is used to page through large result sets.
          To get the next page of results, set this parameter to the value of
          `next_page_token` from the previous response.
    title: Bundles
  ListDataBundlesResponse:
    type: object
    properties:
      data_bundles:
        type: array
        items:
          $ref: '#/definitions/DataBundle'
        description: The list of Data Bundles.
      next_page_token:
        type: string
        description: |-
          The continuation token, which is used to page through large result sets.
          Provide this value in a subsequent request to return the next page of
          results. This field will be empty if there aren't any additional results.
  ListDataObjectsRequest:
    type: object
    properties:
      alias:
        type: string
        description: |-
          OPTIONAL
          If provided will only return Data Objects with the given alias.
      url:
        type: string
        description: |-
          OPTIONAL
          If provided will return only Data Objects with a that URL matches
          this string.
      checksum:
        $ref: '#/definitions/ChecksumRequest'
        title: |-
          OPTIONAL
          If provided will only return data object messages with the provided
          checksum. If the checksum type is provided
      page_size:
        type: integer
        format: int32
        description: |-
          OPTIONAL
          Specifies the maximum number of results to return in a single page.
          If unspecified, a system default will be used.
      page_token:
        type: string
        description: |-
          OPTIONAL
          The continuation token, which is used to page through large result sets.
          To get the next page of results, set this parameter to the value of
          `next_page_token` from the previous response.
    title: |-
      /-------------------------------------------------------------------
      A request to list all objects in a dataset
      /-------------------------------------------------------------------
  ListDataObjectsResponse:
    type: object
    properties:
      data_objects:
        type: array
        items:
          $ref: '#/definitions/DataObject'
        description: The list of Data Objects.
      next_page_token:
        type: string
        description: |-
          The continuation token, which is used to page through large result sets.
          Provide this value in a subsequent request to return the next page of
          results. This field will be empty if there aren't any additional results.
    title: |-
      /-------------------------------------------------------------------
      A list of data objects
      /-------------------------------------------------------------------
  URL:
    type: object
    properties:
      url:
        type: string
        description: |-
          REQUIRED
          A URL that can be used to access the file.
      system_metadata:
        $ref: '#/definitions/SystemMetadata'
      user_metadata:
        $ref: '#/definitions/UserMetadata'
  UpdateDataBundleRequest:
    type: object
    properties:
      data_bundle_id:
        type: string
        title: REQUIRED
      data_bundle:
        $ref: '#/definitions/DataBundle'
        description: |-
          REQUIRED
          The new Data Bundle content.
  UpdateDataBundleResponse:
    type: object
    properties:
      data_bundle_id:
        type: string
        description: |-
          REQUIRED
          The identifier of the Data Bundle updated.
  UpdateDataObjectRequest:
    type: object
    properties:
      data_object_id:
        type: string
        description: |-
          REQUIRED
          The identifier of the Data Object to be updated.
      data_object:
        $ref: '#/definitions/DataObject'
        description: |-
          REQUIRED
          The new Data Object for this identifier.
  UpdateDataObjectResponse:
    type: object
    properties:
      data_object_id:
        type: string
        description: |-
          REQUIRED
          The identifier of the Data Object updated.
